services:
  books: 
    build: .
    image: books
    container_name: books
    hostname: books
    restart: always
    volumes:
      - ./src:/servico
    command: flask --app services/books.py run --host=0.0.0.0 --debug
    environment:
      - DATABASE_CONNECTION_STRING=postgresql://postgres:mysecretpassword@books_db:5432/bookstore
    ports:
      - 5001:5000
    depends_on:
      - books_db
  
  books_db:
    image: postgres
    container_name: books_db
    hostname: books_db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./src/database_population/create_books_database.sql:/docker-entrypoint-initdb.d/init.sql

  clients: 
    build: .
    image: clients
    container_name: clients
    hostname: clients
    restart: always
    volumes:
      - ./src:/servico
    command: flask --app services/clients.py run --host=0.0.0.0 --debug
    environment:
      - DATABASE_CONNECTION_STRING=postgresql://postgres:mysecretpassword@clients_db:5432/bookstore
    ports:
      - 5002:5000
    depends_on:
      - clients_db

  clients_db:
    image: postgres
    container_name: clients_db
    hostname: clients_db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./src/database_population/create_clients_database.sql:/docker-entrypoint-initdb.d/init.sql

  rentals: 
    build: .
    image: rentals
    container_name: rentals
    hostname: rentals
    restart: always
    volumes:
      - ./src:/servico
    command: flask --app services/rentals.py run --host=0.0.0.0 --debug
    environment:
      - DATABASE_CONNECTION_STRING=postgresql://postgres:mysecretpassword@rentals_db:5432/bookstore
    ports:
      - 5003:5000
    depends_on:
      - rentals_db

  rentals_db:
    image: postgres
    container_name: rentals_db
    hostname: rentals_db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./src/database_population/create_rentals_database.sql:/docker-entrypoint-initdb.d/init.sql

